### ISSUE TITLE
noiseImage method leaking memory

### ISSUE THREAD

**Issue by docvvf** [obolton/OBMenuBarWindow#1]
Hi,

noticed that in the noiseImage method a call to free() should be added to balance this malloc(): 

unsigned char *data = malloc(bytes); 

The class is otherwise leaking memory, which I noticed with Instruments. BTW, thanks for writing  this control, it is very elegant!

vvf

**Comment by obolton** [comment]
Well spotted @docvvf, thanks for bringing this to my attention! I have made the fix.
