### ISSUE TITLE
Problem when trying to change the initial distance to menubar

### ISSUE THREAD

**Issue by coryoso** [obolton/OBMenuBarWindow#3]
When you change [self originForAttachedState] so the window has a distance to the menubar, it "wiggles" on start. The window starts with no distance but then changes the distance. 
A const named initialDistance would be great

**Comment by obolton** [comment]
Hi,

Use the `distanceFromMenuBar` property to set the distance of the window from the menu bar. The `originForAttachedState` method is only intended to be used internally.
